// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdiUrD5Jw9TYatCxCDb00H0h9bhQL3VLY',
    appId: '1:681358027497:web:e72df7ce706e00ece69e78',
    messagingSenderId: '681358027497',
    projectId: 'sewa-motor-3fe46',
    authDomain: 'sewa-motor-3fe46.firebaseapp.com',
    storageBucket: 'sewa-motor-3fe46.appspot.com',
    measurementId: 'G-VKYJ0PTJ98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp1PdRQ5lQvLEtSlunsZQY2yMXFSYYKTA',
    appId: '1:681358027497:android:3e04c5b983b06035e69e78',
    messagingSenderId: '681358027497',
    projectId: 'sewa-motor-3fe46',
    storageBucket: 'sewa-motor-3fe46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8v5fmW7igGN3AH6tnu21krDDxVsubjVE',
    appId: '1:681358027497:ios:a121c473263a11b8e69e78',
    messagingSenderId: '681358027497',
    projectId: 'sewa-motor-3fe46',
    storageBucket: 'sewa-motor-3fe46.appspot.com',
    iosBundleId: 'com.example.sewaMotor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8v5fmW7igGN3AH6tnu21krDDxVsubjVE',
    appId: '1:681358027497:ios:a121c473263a11b8e69e78',
    messagingSenderId: '681358027497',
    projectId: 'sewa-motor-3fe46',
    storageBucket: 'sewa-motor-3fe46.appspot.com',
    iosBundleId: 'com.example.sewaMotor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdiUrD5Jw9TYatCxCDb00H0h9bhQL3VLY',
    appId: '1:681358027497:web:675daa9cb0d7e3ade69e78',
    messagingSenderId: '681358027497',
    projectId: 'sewa-motor-3fe46',
    authDomain: 'sewa-motor-3fe46.firebaseapp.com',
    storageBucket: 'sewa-motor-3fe46.appspot.com',
    measurementId: 'G-J02NT7K4LT',
  );
}
